### ISSUE TITLE
Where are the artifacts gone?

### ISSUE THREAD

**Issue by JohnPreston** [confluentinc/csid-secrets-providers#169]
Hello.

Since 1.0.5, no more artifacts with the libs are compiled and provided.
Why?  Can you please make sure the automation publishes the .zip with the lib and jars please?

Thank you,

**Comment by ddonaghy-c** [comment]
Hey John

All the latest artefacts are published on the Confluent Hub at the URLs below; but I will attach up the versions onto the release folders on github as well

https://www.confluent.io/hub/confluentinc/csid-secrets-provider-azure
https://www.confluent.io/hub/confluentinc/csid-secrets-provider-vault
https://www.confluent.io/hub/confluentinc/csid-secrets-provider-aws
https://www.confluent.io/hub/confluentinc/csid-secrets-provider-gcloud
https://www.confluent.io/hub/confluentinc/csid-secrets-provider-k8s

**Comment by JohnPreston** [comment]
Neat! Sorry if I missed the docs or the info in the READMEs/Changelog.

Thank you!
