### ISSUE TITLE
When we use vaultProvider with AppRole and custom mount, the authentication use UserPass instead of AppRole

### ISSUE THREAD

**Issue by ahmedtoumi** [confluentinc/csid-secrets-providers#184]
### Vault Provider

When using Vault provider, we need some configs like :

> vault.address = https://vault.xxxx.com
	vault.auth.method = AppRole
	**vault.auth.mount = approle-xxx**
	vault.auth.role = xxxxx
	vault.auth.secret = [hidden]
	vault.namespace = 
	vault.prefixpath = 
	vault.secrets.version = 2

but unfortunately, when we specify a custome **vault.auth.mount**, the java code force the use of **UserPass** login instead of **AppRole** in this [line](https://github.com/confluentinc/csid-secrets-providers/blob/5fea1bc67d059adad49c6b1bc66a2744bcda5d92/vault/src/main/java/io/confluent/csid/config/provider/vault/AuthHandler.java#L278)

this code

     public AuthResult execute(VaultConfigProviderConfig config, Vault vault) throws VaultException {
      AuthResponse response;
      if (isNullOrEmpty(config.mount)) {
        log.trace("execute() - calling loginByAppRole('{}', '*****')", config.role);
        response = vault.auth().loginByAppRole(config.role, config.secret);
      } else {
        log.trace("execute() - calling loginByUserPass('{}', ****, '{}')", config.username, config.mount);
        response = vault.auth().loginByUserPass(config.username, config.password, config.mount);
      }
      return result(response);
    }

should be replaced by this one

      public AuthResult execute(VaultConfigProviderConfig config, Vault vault) throws VaultException {
      AuthResponse response;

      if (isNullOrEmpty(config.mount)) {
        log.trace("execute() - calling loginByAppRole('{}', '*****')", config.role);
        response = vault.auth().loginByAppRole(config.role, config.secret);
      } else {
        log.trace("execute() - calling loginByAppRole('{}', '{}', ****)", config.mount, config.role);
        response = vault.auth().loginByAppRole( config.mount, config.role, config.secret);
      }
      return result(response);
    }

**Comment by ahmedtoumi** [comment]
I'm preparing this small PR, but blocking for our urgent usecase

**Comment by ddonaghy-c** [comment]
Hello @ahmedtoumi thank you for your submission - yes this seems to be a long standing bug here and a good catch as well.  Your PR above references you were looking to add tests to this is that correct?

**Comment by ahmedtoumi** [comment]
hello @ddonaghy-c ,
I tested it in real environment and it's working well
do you suggest to add some unit/IT tests ?

**Comment by ddonaghy-c** [comment]
hello @ahmedtoumi - this new version has been published to the Confluent Hub and should hopefully appear for download at some point today; release details will be updated soon on the repo

**Comment by ahmedtoumi** [comment]
excellent new thanks @ddonaghy-c
