### ISSUE TITLE
command to install is wrong

### ISSUE THREAD

**Issue by NathanT02** [confluentinc/csid-secrets-providers#327]
the command in the docs says `confluent-hub install confluentinc/kafka-config-provider-aws:latest` this gives an `Error: plugin not found`.

The correct command is `confluent-hub install confluentinc/csid-secrets-provider-aws:latest`.

Just for reference for future readers

**Comment by stephenheg** [comment]
Hi @NathanT02 , thanks for highlighting this. 

We have merged in a PR to resolve the old naming of `csid-config` and `kafka-config`.
